CFLAGS = -std=gnu11 -Wall -Wextra -lm -fopenmp -O2

.PHONY: all
all: ex2 ex2_bugfree ex2_better

.PHONY: clean
clean:
	$(RM) ex2 ex2_bugfree ex2_better

ex2: ex2.c
ex2_bugfree: ex2_bugfree.c
ex2_better: ex2_better.c
